# Generated by Django 3.1.1 on 2020-09-29 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnh', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=13)),
                ('foto', models.ImageField(upload_to='Motoristas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Motoristas',
            },
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('modelo', models.CharField(max_length=20)),
                ('vagas', models.IntegerField(blank=True, null=True)),
                ('horario', models.DateTimeField(blank=True, null=True)),
                ('foto_van', models.ImageField(upload_to='Vans')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.motorista')),
            ],
            options={
                'db_table': 'Vans',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=7)),
                ('endereco', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=13)),
                ('foto', models.ImageField(upload_to='alunos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('van', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rest_api.van')),
            ],
            options={
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
